kursinis/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/upload/', views.upload_file, name='upload'),
    # path('upload/success', views.upload_success, name='success')
    path('passed', views.passed_tests, name='passed'),
    path('failed', views.failed_tests, name='failed')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    question_details = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class TestCase(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    test_input = models.CharField(max_length=500, blank=True)
    test_output = models.CharField(max_length=500)

    def __str__(self):
        return self.test_input + ' -> ' + self.test_output

polls/forms.py
from django import forms


class UploadFileForm(forms.Form):
    # title = forms.CharField(max_length=50)
    file = forms.FileField()

polls/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404, redirect

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View

from django.shortcuts import render
from django.views.generic.detail import SingleObjectMixin

from .forms import UploadFileForm
from .services import handle_uploaded_file

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return published questions."""
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def upload_file(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            tests_passed = handle_uploaded_file(request.FILES['file'], question.testcase_set.all())
            if tests_passed:
                return redirect(reverse('polls:passed'))
            else:
                return redirect(reverse('polls:failed'))
        # else:
        #     msg = 'Errors: %s' % form.errors.as_text()
        #     return HttpResponse(msg, status=400)
    else:
        form = UploadFileForm()
    return render(request, 'polls/detail.html', {
        'question': question,
        'error_message': "Nepasirinktas failas",
    })
    # return HttpResponseRedirect(request, 'polls/detail.html', {'form': form})


# def upload_file(request):
#     if request.method == 'POST':
#         form = UploadFileForm(request.POST, request.FILES)
#         if form.is_valid():
#             handle_uploaded_file(request.FILES['file'])
#             return redirect('polls:success')
#     else:
#         form = UploadFileForm()
#     return render(request, 'polls/upload.html', {'form': form})


def passed_tests(request):
    return render(request, 'polls/passed_tests.html')


def failed_tests(request):
    return render(request, 'polls/failed_tests.html')

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="lt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Detail</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}">
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Pitonas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'polls:index' %}">Užduotys</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
        <form action="{% url 'polls:upload' question.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                <p>{{ question.question_details }}</p>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

                <div class="mb-3">
                    <label for="formFile" class="form-label">Įkelk sprendimo failą: </label>
                    <input class="form-control" type="file" name="file" id="formFile" accept="*/*">
                </div>
        {#        <input id="uploadbutton" type="file" value="Browse" name="file" accept="*/*"/>#}
            </fieldset>
            <input type="submit" class="btn btn-primary" value="Įkelti">
        </form>
    </div>
</body>
</html>

polls/templates/polls/detail_for_votes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
</body>
</html>

polls/templates/polls/failed_tests.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" >
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Pitonas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'polls:index' %}">Užduotys</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container w-50 p-3">
        <div class="card mb-3 text-center">
            <img src="{% static 'img/tryagain.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h1 class="card-title">Programa nepraėjo visų testų. Bandyk dar kartą!</h1>
            </div>
        </div>
    </div>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="lt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Starter page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" >
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
</head>
<body>
{#{% if latest_question_list %}#}
{#    <ul>#}
{#    {% for question in latest_question_list %}#}
{#        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>#}
{#    {% endfor %}#}
{#    </ul>#}
{#{% else %}#}
{#    <p>No polls are available.</p>#}
{#{% endif %}#}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Pitonas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'polls:index' %}">Užduotys</a>
          </div>
        </div>
      </div>
    </nav>

    {% if latest_question_list %}
        <div class="container">
            <div class="list-group">
            {% for question in latest_question_list %}
                <a href="{% url 'polls:detail' question.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ question.question_text }}</h5>
    {#              <small class="text-muted">3 days ago</small>#}
                </div>
    {#            <p class="mb-1">Some placeholder content in a paragraph.</p>#}
    {#            <small class="text-muted">And some muted small print.</small>#}
                </a>
            {% endfor %}
            </div>
        </div>
    {% else %}
        <p>Nėra užduočių.</p>
    {% endif %}

{#<a href="{% url 'polls:upload' %}">Upload file</a>#}
</body>
</html>

polls/templates/polls/passed_tests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" >
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Pitonas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" href="{% url 'polls:index' %}">Užduotys</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container w-50 p-3">
        <div class="card mb-3 text-center">
            <img src="{% static 'img/goodjob.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
                <h1 class="card-title">Programa praėjo visus testus. Sveikinimai!</h1>
            </div>
        </div>
    </div>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Results</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" >
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

polls/templates/polls/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}" >
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
</head>
<body>
{#        <form action="{% url 'polls:upload' %}" method="post" enctype="multipart/form-data">#}
{#            {% csrf_token %}#}
{#            <p>{{ form.non_field_errors }}</p>#}
{#            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>#}
{#            <p>#}
{#                {{ form.docfile.errors }}#}
{#                {{ form.docfile }}#}
{#            </p>#}
{#            <p><input type="submit" value="Upload" /></p>#}
{#        </form>#}

{% block content %}
    <h1>Upload solution</h1>
    <form action="{% url 'polls:upload'%}" method="post" enctype="multipart/form-data">
         {% csrf_token %}

        <input id="uploadbutton" type="file" value="Browse" name="file" accept="*/*" />
        <input type="submit" value="Upload" />
    </form>
{% endblock %}

</body>
</html>

polls/templates/polls/upload_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}">
    <script src="{% static 'polls/js/bootstrap.bundle.js' %}"></script>
</head>
<body>

<h1>Thanks for the upload :)</h1>
</body>
</html>